version: 1.0.{build}
environment:
  matrix:
  - var1: var1
  - var2: var2
  - var3: var3
  - var4: var4
  - var5: var5
build:
  verbosity: detailed
after_test:
- ps: for ($i = 0; $i -lt 3500; $i++) {Write-host "Message $i"; Add-AppveyorMessage -Message "Message $i"}
